export const COMPARISON_DISCLAIMER =
  "All figures are estimates for comparison purposes only. Actual fees, exchange rates, and settlement times may vary. TrueRate does not execute transfers and is not a financial advisor.";

export const EXPORT_FOOTER_DISCLAIMER =
  "Generated by TrueRate. Estimates only — verify with your provider before sending money.";

export const COMPARISON_FORM_DISCLAIMER =
  "Rates and fees are estimated and refreshed periodically. Not financial advice.";
