export const SUPPORTED_CURRENCIES = [
  { code: "USD", name: "US Dollar" },
  { code: "EUR", name: "Euro" },
  { code: "GBP", name: "British Pound" },
  { code: "INR", name: "Indian Rupee" },
  { code: "MXN", name: "Mexican Peso" },
  { code: "PHP", name: "Philippine Peso" },
] as const;

export const MVP_CORRIDORS = [
  {
    sourceCountry: "IN",
    destCountry: "GB",
    sourceCurrency: "INR",
    destCurrency: "GBP",
    label: "India → United Kingdom",
  },
  {
    sourceCountry: "IN",
    destCountry: "US",
    sourceCurrency: "INR",
    destCurrency: "USD",
    label: "India → United States",
  },
  {
    sourceCountry: "IN",
    destCountry: "EU",
    sourceCurrency: "INR",
    destCurrency: "EUR",
    label: "India → Eurozone",
  },
  {
    sourceCountry: "IN",
    destCountry: "MX",
    sourceCurrency: "INR",
    destCurrency: "MXN",
    label: "India → Mexico",
  },
  {
    sourceCountry: "IN",
    destCountry: "PH",
    sourceCurrency: "INR",
    destCurrency: "PHP",
    label: "India → Philippines",
  },
  {
    sourceCountry: "US",
    destCountry: "IN",
    sourceCurrency: "USD",
    destCurrency: "INR",
    label: "United States → India",
  },
  {
    sourceCountry: "GB",
    destCountry: "IN",
    sourceCurrency: "GBP",
    destCurrency: "INR",
    label: "United Kingdom → India",
  },
  {
    sourceCountry: "EU",
    destCountry: "IN",
    sourceCurrency: "EUR",
    destCurrency: "INR",
    label: "Eurozone → India",
  },
  {
    sourceCountry: "MX",
    destCountry: "IN",
    sourceCurrency: "MXN",
    destCurrency: "INR",
    label: "Mexico → India",
  },
  {
    sourceCountry: "PH",
    destCountry: "IN",
    sourceCurrency: "PHP",
    destCurrency: "INR",
    label: "Philippines → India",
  },
  {
    sourceCountry: "US",
    destCountry: "MX",
    sourceCurrency: "USD",
    destCurrency: "MXN",
    label: "United States → Mexico",
  },
  {
    sourceCountry: "US",
    destCountry: "PH",
    sourceCurrency: "USD",
    destCurrency: "PHP",
    label: "United States → Philippines",
  },
  {
    sourceCountry: "US",
    destCountry: "GB",
    sourceCurrency: "USD",
    destCurrency: "GBP",
    label: "United States → United Kingdom",
  },
  {
    sourceCountry: "US",
    destCountry: "EU",
    sourceCurrency: "USD",
    destCurrency: "EUR",
    label: "United States → Eurozone",
  },
  {
    sourceCountry: "MX",
    destCountry: "US",
    sourceCurrency: "MXN",
    destCurrency: "USD",
    label: "Mexico → United States",
  },
  {
    sourceCountry: "PH",
    destCountry: "US",
    sourceCurrency: "PHP",
    destCurrency: "USD",
    label: "Philippines → United States",
  },
  {
    sourceCountry: "GB",
    destCountry: "US",
    sourceCurrency: "GBP",
    destCurrency: "USD",
    label: "United Kingdom → United States",
  },
  {
    sourceCountry: "EU",
    destCountry: "US",
    sourceCurrency: "EUR",
    destCurrency: "USD",
    label: "Eurozone → United States",
  },
  {
    sourceCountry: "GB",
    destCountry: "MX",
    sourceCurrency: "GBP",
    destCurrency: "MXN",
    label: "United Kingdom → Mexico",
  },
  {
    sourceCountry: "GB",
    destCountry: "PH",
    sourceCurrency: "GBP",
    destCurrency: "PHP",
    label: "United Kingdom → Philippines",
  },
  {
    sourceCountry: "GB",
    destCountry: "EU",
    sourceCurrency: "GBP",
    destCurrency: "EUR",
    label: "United Kingdom → Eurozone",
  },
  {
    sourceCountry: "EU",
    destCountry: "GB",
    sourceCurrency: "EUR",
    destCurrency: "GBP",
    label: "Eurozone → United Kingdom",
  },
  {
    sourceCountry: "EU",
    destCountry: "MX",
    sourceCurrency: "EUR",
    destCurrency: "MXN",
    label: "Eurozone → Mexico",
  },
  {
    sourceCountry: "EU",
    destCountry: "PH",
    sourceCurrency: "EUR",
    destCurrency: "PHP",
    label: "Eurozone → Philippines",
  },
  {
    sourceCountry: "MX",
    destCountry: "PH",
    sourceCurrency: "MXN",
    destCurrency: "PHP",
    label: "Mexico → Philippines",
  },
  {
    sourceCountry: "PH",
    destCountry: "MX",
    sourceCurrency: "PHP",
    destCurrency: "MXN",
    label: "Philippines → Mexico",
  },
] as const;

export const COMPARISON_PRIORITIES = [
  { value: "cheapest", label: "Lowest cost" },
  { value: "highest_received", label: "Most received" },
  { value: "fastest", label: "Fastest" },
  { value: "balanced", label: "Best balance" },
  { value: "traditional", label: "Bank & remittance" },
  { value: "digital", label: "Crypto & stablecoins" },
] as const;

export const COMPARISON_PRIORITY_VALUES = COMPARISON_PRIORITIES.map(
  (option) => option.value,
);

export const PROVIDER_TYPE_LABELS: Record<string, string> = {
  swift: "SWIFT",
  remittance: "Remittance",
  stablecoin: "Stablecoin",
  crypto: "Crypto",
};
